name: CI

on:
  push:
    branches:
      - main

jobs:
  # ******** test in pure python & uv venv first  *******
  integrate-and-test-pure-py-app:
    runs-on: ubuntu-latest
    env:
      MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
      MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
      MLFLOW_TRACKING_USERNAME: ${{secrets.MLFLOW_TRACKING_USERNAME}}
      MLFLOW_TRACKING_PASSWORD: ${{secrets.MLFLOW_TRACKING_PASSWORD}}
      DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_USER_TOKEN}}

    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: python installation
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: install uv
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv

      - name: install dependecies
        run: uv sync --frozen --no-install-project

      - name: run python test
        run: uv run python -m pytest

  # ******** test in docker container second *******

  integrate-and-test-docker-app:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6

      - name: run docker compose
        env:
          MONGO_USERNAME: ${{secrets.MONGO_USERNAME}}
          MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
          MLFLOW_TRACKING_USERNAME: ${{secrets.MLFLOW_TRACKING_USERNAME}}
          MLFLOW_TRACKING_PASSWORD: ${{secrets.MLFLOW_TRACKING_PASSWORD}}
          DAGSHUB_USER_TOKEN: ${{secrets.DAGSHUB_USER_TOKEN}}
        run: docker compose up -d --build --wait

      - name: test the app
        run: |
          docker compose exec myapp uv run python -m pytest
